version: '3.8'

services:
  # api:
  #   container_name: app-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     - PORT=3001
  #     - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-some-secret}
  #     - NODE_ENV=${NODE_ENV:-development}
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   depends_on:
  #     - db

  # website:
  #   container_name: app-website
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.website
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - PORT=3000
  #     - API_URL=http://api:3001
  #     - NODE_ENV=${NODE_ENV:-development}
  #   restart: unless-stopped
  #   depends_on:
  #     - api
  #   networks:
  #     - app-network

  db:
    image: postgres:14
    container_name: app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'

networks:
  app-network:
    driver: bridge
    name: app-network

volumes:
  postgres-data:
