FROM imbios/bun-node:latest-20-debian AS builder
WORKDIR /app
ENV NODE_ENV=production
COPY . .
RUN bun install
RUN bun run --cwd apps/api build

# Build the production image
FROM gcr.io/distroless/base
WORKDIR /app

# Copy necessary files from the builder stage
COPY --from=builder --chmod=755 /app/apps/api/dist/server server

ENV NODE_ENV=production
ARG PORT=3001
ENV PORT=${PORT}
EXPOSE $PORT

CMD ["./server"]

